kind: Deployment
apiVersion: apps/v1
metadata:
  name: m-caj-payment
  labels:
    app: m-caj-payment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-caj-payment
      version: v1
  template:
    metadata:
      labels:
        app: m-caj-payment
        version: v1
    spec:
      containers:
        - name: m-caj-payment
          image: '{{ .Values.image.payment.repo }}:{{ .Values.image.payment.tag }}'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_DIALECT
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_DRIVER
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PXD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PXD